import type { PricingPlan } from "./types";

/** Hybrid B2B2C pricing — from MilkyChat Business Model Recommendation v1 */
export const PARENT_PLANS: PricingPlan[] = [
  {
    id: "free",
    name: "Free",
    audience: "parent",
    monthlyPrice: 0,
    yearlyPrice: 0,
    priceLabel: "Always free",
    description: "A rich village experience — timeline, moments, circles, and educator updates.",
    features: [
      "Child-centric timeline of moments & posts",
      "Rich media sharing (photo, video, notes)",
      "Circles with privacy controls",
      "Parent ↔ educator messaging",
      "Kid profiles & basic search",
      "Notifications & village reminders",
    ],
    cta: "Stay on Free",
  },
  {
    id: "plus",
    name: "Plus",
    audience: "parent",
    monthlyPrice: 6.99,
    yearlyPrice: 69,
    priceLabel: "$6.99/mo or $69/yr",
    description: "Convenience and memory preservation without clutter.",
    features: [
      "Everything in Free",
      "Unlimited HD storage & auto-backup",
      "Smart albums & basic AI organization",
      "Print book discounts",
      "Ad-light experience",
    ],
    cta: "Upgrade to Plus",
  },
  {
    id: "premium",
    name: "Premium",
    audience: "parent",
    monthlyPrice: 12.99,
    yearlyPrice: 129,
    priceLabel: "$12.99/mo or $129/yr",
    description: "AI-powered Child Journey Insights — the full story of their growth.",
    features: [
      "Everything in Plus",
      "AI Child Journey Insights (multimodal)",
      "Family Coordination Agent & weekly digests",
      "Personalized developmental recommendations",
      "Premium albums & keepsakes",
      "Advanced circle / guardian controls",
      "Priority support & early features",
    ],
    highlighted: true,
    cta: "Upgrade to Premium",
  },
];

export const B2B_PLANS: PricingPlan[] = [
  {
    id: "starter",
    name: "Starter",
    audience: "b2b",
    monthlyPrice: 149,
    yearlyPrice: null,
    priceLabel: "$99–199/mo or $1.50–2.50/child",
    description: "Small daycares & single centers under 100 children.",
    features: [
      "Basic admin & attendance",
      "Parent timeline, moments & chat",
      "Basic reports",
      "Free parent app for all families",
    ],
    cta: "Start pilot",
  },
  {
    id: "growth",
    name: "Growth",
    audience: "b2b",
    monthlyPrice: null,
    yearlyPrice: null,
    priceLabel: "$2.00–3.50 / child / mo",
    description: "Preschools & centers (100–400 kids) — core volume tier.",
    features: [
      "Full admin + billing integration",
      "Educator bulk tools & templates",
      "Advanced engagement analytics",
      "Full parent free + premium funnel",
    ],
    highlighted: true,
    cta: "Talk to sales",
  },
  {
    id: "premium",
    name: "Premium / Chain",
    audience: "b2b",
    monthlyPrice: null,
    yearlyPrice: null,
    priceLabel: "$2.50–4.50+ / child / mo",
    description: "Multi-site centers, international schools, networks.",
    features: [
      "Everything in Growth",
      "AI insights dashboard for educators",
      "API / integrations & priority support",
      "Compliance modules · optional white-label",
    ],
    cta: "Request quote",
  },
  {
    id: "enterprise",
    name: "Enterprise",
    audience: "b2b",
    monthlyPrice: null,
    yearlyPrice: null,
    priceLabel: "Custom",
    description: "Large districts & regional operators with SLA needs.",
    features: [
      "Full platform + custom integrations",
      "Dedicated onboarding & training",
      "Advanced opt-in data insights",
      "Volume discounts & enterprise SLA",
    ],
    cta: "Contact enterprise",
  },
];

export const PLAN_FEATURE_GATES = {
  free: {
    storageGb: 2,
    aiJourney: false,
    familyAssistant: false,
    smartAlbums: false,
    educatorCopilot: false,
  },
  plus: {
    storageGb: Infinity,
    aiJourney: false,
    familyAssistant: false,
    smartAlbums: true,
    educatorCopilot: false,
  },
  premium: {
    storageGb: Infinity,
    aiJourney: true,
    familyAssistant: true,
    smartAlbums: true,
    educatorCopilot: true,
  },
} as const;
